#!/bin/bash

# Update packages
sudo yum update -y

# Install Java 17
sudo yum install java-17-amazon-corretto -y

# Install wget and tar
sudo yum install wget tar -y

# Go to /opt
cd /opt

# Download Maven
sudo wget https://archive.apache.org/dist/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz

# Extract Maven
sudo tar -xzf apache-maven-3.9.9-bin.tar.gz

# Rename directory
sudo mv apache-maven-3.9.9 maven

# Configure environment variables
sudo tee /etc/profile.d/maven.sh > /dev/null <<EOF
export M2_HOME=/opt/maven
export PATH=\$M2_HOME/bin:\$PATH
EOF

# Permission
sudo chmod +x /etc/profile.d/maven.sh

# Load environment variables
source /etc/profile.d/maven.sh

# Verify
java -version
mvn -v
