#!/bin/bash

# Update packages
sudo yum update -y

# Install Java 17
sudo yum install java-17-amazon-corretto -y

# Install wget and tar
sudo yum install wget tar -y

# Move to /opt directory
cd /opt

# Download Maven 3.9.9
sudo wget https://archive.apache.org/dist/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz

# Extract Maven
sudo tar -xvzf apache-maven-3.9.9-bin.tar.gz

# Rename Maven directory
sudo mv apache-maven-3.9.9 maven

# Configure environment variables
sudo tee /etc/profile.d/maven.sh > /dev/null <<EOF
export M2_HOME=/opt/maven
export PATH=\${M2_HOME}/bin:\${PATH}
EOF

# Give execute permission
sudo chmod +x /etc/profile.d/maven.sh

# Load variables
source /etc/profile.d/maven.sh

# Verify installations
java -version
mvn -v
